version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3001:3000'
    volumes:
      - './server:/home/node/template/express-js'
      - '/home/node/template/express-js/node_modules'

  nginx:
    build:
      context: ./nginx
      args:
        - WEB_REVERSE_PROXY_PORT=8000
        - WEB_SSL=true
        - SELF_SIGNED=false
        - NO_DEFAULT=false
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - ./nginx/logs/:/var/log/nginx
      - ./certbot/certs/:/var/certs

  certbot:
    build:
      context: ./certbot
    links:
      - nginx
    volumes:
      - ./certbot/letsencrypt/:/var/www/letsencrypt
      - ./certbot/certs/:/var/certs
